FROM golang:1.8
MAINTAINER mbrooks

RUN apt-get update && \
    apt-get install -y pkg-config libsystemd-dev git gcc curl && \
    apt-get purge -y --auto-remove && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /go/src/github.com/temal-/journalbeat && mkdir -p /data
COPY . /go/src/github.com/temal-/journalbeat
WORKDIR /go/src/github.com/temal-/journalbeat
RUN go build
